### ISSUE TITLE
Build tools like a LICENSE File.

### ISSUE THREAD

**Issue by ghost** [tailwindlabs/tailwindcss-line-clamp#12]
### What version of @tailwindcss/line-clamp are you using?

n/a

### What version of Node.js are you using?

n/a

### What browser are you using?

n/a

### What operating system are you using?

n/a

### Reproduction repository

n/a

### Describe your issue

Missing LICENSE file.

**Comment by adamwathan** [comment]
Dunno how we missed that, thanks!
