### ISSUE TITLE
Update README - Install as a dev dependency

### ISSUE THREAD

**Issue by steve-marmalade** [tailwindlabs/tailwindcss-line-clamp#15]
### What version of @tailwindcss/line-clamp are you using?

v0.3.1

### What version of Node.js are you using?

v17.3.0

### What browser are you using?

N/A

### What operating system are you using?

macOS

### Reproduction repository

See below

### Describe your issue

Given that the [TailwindCSS installation docs](https://tailwindcss.com/docs/installation) instruct the user to run `npm install -D tailwindcss`, the README for this repo should be updated to do `npm install -D @tailwindcss/line-clamp` and `yarn add --dev @tailwindcss/line-clamp`.

It's a small nit, but it surfaced as I was upgrading to modern yarn and needed to address the warning that line-clamp had an unmet peer dependency on tailwind. The issue was that line-clamp was a regular dependency and tailwind was a devDependency; moving line-clamp to dev resolved the warning.

Thanks for such a useful plugin!

**Comment by adamwathan** [comment]
Done, thanks.
