### ISSUE TITLE
Tailwind CSSv3.0.23+ doesn't properly support variants

### ISSUE THREAD

**Issue by benlei** [tailwindlabs/tailwindcss-line-clamp#16]
### What version of @tailwindcss/line-clamp are you using?

v0.3.1

### What version of Node.js are you using?

v16.13.0

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### Reproduction repository

N/A

### Describe your issue

Offending issue starts at https://github.com/tailwindlabs/tailwindcss-line-clamp/blob/master/src/index.js#L10

But if you check https://tailwindcss.com/docs/plugins (v3.0.23)

You'll notice that it doesn't have a `variants` field anymore. I got it to work by renaming it to `addVariant`.

**Comment by adamwathan** [comment]
Sorry what’s the actual issue here? We do still include a variants function in v3 that’s a no-op so people can write plugins that work for both v2 and v3, so this plugin should work fine. What’s the actual problem you’re seeing?

**Comment by adamwathan** [comment]
Going to close this, if this is still an issue though feel free to open a new issue and include the information I asked for in my last comment so I better understand the problem 👍
