### ISSUE TITLE
Strange behavior when strings and with integer characters

### ISSUE THREAD

**Issue by p3cardoso** [tailwindlabs/tailwindcss-line-clamp#25]
### What version of @tailwindcss/line-clamp are you using?

v0.4.2

### What version of Node.js are you using?

v16.18.0

### What browser are you using?

Chrome 107.0.5304.88 

### What operating system are you using?

Windows 11 Pro

### Reproduction repository

https://github.com/p3cardoso/clamping-test.git

### Describe your issue

Just when truncated text ends with an integer character or some punctuation mark(.,!?), the ellipsis doesn´t appear. If any character is added to the end it will works fine. In my case I have used "&nbsp" to avoid this behavior. I am guessing It need to be a letter at the end of line and not the text itself for line-clamp works perfectly.

**Comment by adamwathan** [comment]
Just for when we look at this, here's a Tailwind Play reproduction, easier than cloning and running a project:

https://play.tailwindcss.com/gH5ly9Xmnb

My guess is this is out of our hands and just how this CSS feature behaves, it's not really anything fancy we are doing here, just setting some CSS properties that do all of this work for us :/

**Comment by adamwathan** [comment]
Another data point — this doesn't appear to have anything to do with numbers, it happens when the content is a single word that is too long for the container:

https://play.tailwindcss.com/sF4VXGY57j

**Comment by p3cardoso** [comment]
I got it. Thank's for the Tailwind Play advice. Yeah, it's about long strings.

**Comment by adamwathan** [comment]
So I forked a [CodePen demo from CSS Tricks](https://css-tricks.com/almanac/properties/l/line-clamp/) to see what happens with just hand-written CSS and unfortunately the results are the same:

https://codepen.io/adamwathan/pen/XWYMaqP

...so this isn't something we can really change/fix within the plugin, just what the browser does for this property in this situation. So going to close this, I think you'll just have to find a different way to handle this in your UI that isn't the CSS line-clamp feature I'm afraid.
