### ISSUE TITLE
Line clamp for parrent element

### ISSUE THREAD

**Issue by dcheglakov** [tailwindlabs/tailwindcss-line-clamp#4]
Hi,

I'm trying to combine `@tailwindcss/typography` and `@tailwindcss/line-clamp`.
In Chrome everything works as expected, but in Safari and Firefox, all child elements are clamped.

```jsx
<div className="flex flex-col lg:flex-row lg:space-x-24">
  {content.map((col) => (
    <div key={col.title}>
      <h3 className="pb-8 font-semibold">{col.title}</h3>
      <Markdown
        options={{ forceBlock: true, forceWrapper: true }}
        className="prose line-clamp-6 lg:prose-lg text-white leading-snug lg:leading-snug"
      >
        {col.content}
      </Markdown>
    </div>
  ))}
</div>
```

Here is **Tailwind Play** to test it out: https://play.tailwindcss.com/nBp0o51bsH

**Comment by neupauer** [comment]
Hi, I have the same problem but I'm not sure if this is currently possible with pure CSS. `-webkit-line-clamp` has a quirk behavior in browsers, especially with multiple `p` tags.

I see that you are using MDX so probably the using JS is the best solution. You can add some flag to the content e.g. `<!--excerpt-end-->` and then split the content in JS `col.content.split('<!--your-flag-->')` and render the first part. Or if you have not access to the content show the first (65 * 6) characters.

But I would also like to see some CSS solution :).

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

I am a little afraid that there is nothing we can do (currently) from a css perspective to fix this issue. I think a JS solution might be needed (or a custom excerpt you create on the backend). That said, there is a solution to apply the line-clamp to each `p` tag, but that will probably not yield the expected result: https://play.tailwindcss.com/WwRKzv3EFO?file=config

**Comment by dcheglakov** [comment]
@RobinMalfait thank you.

@neupauer, unfortunately, data comes from CMS and I can't add  and I need clamp only on the mobile version of the site. But anyway thanks.
