### ISSUE TITLE
More Text Showing After Ellipse

### ISSUE THREAD

**Issue by jrock2004** [tailwindlabs/tailwindcss-line-clamp#9]
### What version of @tailwindcss/line-clamp are you using?

0.2.2

### What version of Node.js are you using?

16.13.0

### What browser are you using?

Firefox

### What operating system are you using?

Linux

### Reproduction repository

https://github.com/jrock2004/anime-store/commit/8722454cfb12738c54de1549620d0f2cc893030c

### Describe your issue

I see the ellipse but text is still showing after the ellipse

![image](https://user-images.githubusercontent.com/655716/139553733-dd2bd619-6168-45f1-b0a1-f3dc4fd627b7.png)

I also tried in Chrome on Linux as well with same result.

You can check out the commit and you need to run `yarn server` and `yarn start` 

Update 1: Tested on Mac Firefox and same result

**Comment by adamwathan** [comment]
Hey! Wrap the `p` tag in a `div`:

https://play.tailwindcss.com/fYiW4PLl3r

Because the `p` is a flex-child, some of the necessary properties to make line-clamp work are being overridden by how direct flex children work in CSS. Wrapping it in a div solves it 👍🏻
